<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useCollection } from '@/composables/useCollection'
import { storage } from '@/data/storage'
import ModuleHeader from '@/shared/components/ModuleHeader.vue'
import AppIcon from '@/shared/components/AppIcon.vue'
import type { BalanceMovement, Daruma } from '@/domain/types'

const route=useRoute();const movements=useCollection<BalanceMovement>('balance_movimientos');const darumas=useCollection<Daruma>('balance_darumas');const hidden=ref(true);const showMovement=ref(false);const showDaruma=ref(false)
const movement=reactive({tipo:'gasto' as 'ingreso'|'gasto',monto:0,categoria:'El nido',nota:''});const goal=reactive({nombre:'',objetivo:0,color:'#C9A86A'})
const categories=['El nido','El cuerpo','El movimiento','El cuidado','Lo inesperado','Lo que construyo'];const colors=['#C0392B','#C9A86A','#F5F0E6','#9B7D9B','#7d9b8a','#5B8DB8','#2C2C2C','#D4849A']
const total=computed(()=>movements.items.value.reduce((sum,item)=>sum+(item.tipo==='ingreso'?item.monto:-item.monto),0));const currency=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0})
async function addMovement(){if(movement.monto<=0)return;await movements.add({...movement,fecha:new Date().toISOString(),fecha_creacion:new Date().toISOString()});movement.monto=0;movement.nota='';showMovement.value=false}
async function addDaruma(){if(!goal.nombre.trim()||goal.objetivo<=0)return;await darumas.add({nombre:goal.nombre.trim(),objetivo:goal.objetivo,acumulado:0,color:goal.color,daruma_transferido:false,fecha_creacion:new Date().toISOString()});goal.nombre='';goal.objetivo=0;showDaruma.value=false}
async function toggleBalance(){hidden.value=!hidden.value;await storage.set('balance_oculto',hidden.value)}
onMounted(async()=>{hidden.value=(await storage.get<boolean>('balance_oculto'))??true;showMovement.value=route.query.action==='movimiento';showDaruma.value=route.query.action==='meta'})
</script>

<template><main class="app-shell balance-view"><ModuleHeader title="Mi Balance"/><section class="balance-hero"><button class="balance-value" type="button" :aria-label="hidden?'Mostrar balance':'Ocultar balance'" @click="toggleBalance"><span>Lo que tengo hoy</span><AppIcon name="balance"/><strong>{{ hidden?'· · · · ·':currency.format(total) }}</strong></button><p>Lo que registro no me define. Me orienta.</p></section><div class="balance-actions"><button class="primary-action" type="button" @click="showMovement=!showMovement">Registrar movimiento</button><button class="secondary-action" type="button" @click="showDaruma=!showDaruma">Nueva meta</button></div>
<form v-if="showMovement" class="inline-ritual" @submit.prevent="addMovement"><div class="segmented"><button v-for="type in ['ingreso','gasto']" :key="type" type="button" :class="{active:movement.tipo===type}" @click="movement.tipo=type as 'ingreso'|'gasto'">{{ type==='ingreso'?'Entra':'Sale' }}</button></div><label class="field">Monto<input v-model.number="movement.monto" type="number" min="1" inputmode="decimal"/></label><label class="field">Categoría<select v-model="movement.categoria"><option v-for="category in categories" :key="category">{{ category }}</option></select></label><label class="field">Una nota, si la necesitas<input v-model="movement.nota"/></label><button class="primary-action" type="submit" :disabled="movement.monto<=0">Guardar</button></form>
<form v-if="showDaruma" class="inline-ritual" @submit.prevent="addDaruma"><label class="field">¿Qué estás construyendo?<input v-model="goal.nombre"/></label><label class="field">Meta<input v-model.number="goal.objetivo" type="number" min="1"/></label><fieldset class="color-choice"><legend>Color de tu Daruma</legend><button v-for="color in colors" :key="color" type="button" :style="{background:color}" :class="{selected:goal.color===color}" :aria-label="color" @click="goal.color=color"/></fieldset><button class="primary-action" type="submit" :disabled="!goal.nombre.trim()||goal.objetivo<=0">Crear Daruma</button></form>
<section class="balance-columns"><article><h2>Movimientos</h2><div v-if="movements.items.value.length" class="record-list"><div v-for="item in [...movements.items.value].reverse()" :key="item.id" class="record-card"><div><h3>{{ item.nota||item.categoria }}</h3><p>{{ item.categoria }}</p></div><strong :class="item.tipo">{{ item.tipo==='ingreso'?'+':'−' }} {{ currency.format(item.monto) }}</strong></div></div><p v-else class="empty-copy">Sin registros aún. Ver es la primera forma de cuidarte.</p></article><article><h2>Lo que construyo</h2><div v-if="darumas.items.value.length" class="daruma-grid"><article v-for="daruma in darumas.items.value" :key="daruma.id" class="daruma-card" :style="{'--daruma':daruma.color,'--progress':`${Math.min(100,daruma.acumulado/daruma.objetivo*100)}%`}"><span class="daruma-shape"/><h3>{{ daruma.nombre }}</h3><p>{{ currency.format(daruma.acumulado) }} de {{ currency.format(daruma.objetivo) }}</p></article></div><p v-else class="empty-copy">Lo que todavía no nombraste, aquí puede tomar forma.</p></article></section></main></template>
